// #include "rust/cxx.h"
// #include "aligned-simd-rs/src/ffi.rs.h"  // generated by cxx-build

// int main() {
//     // Create a 32-element buffer (multiple of 8 for AVX), all 1.0f
//     auto buf = aligned_buffer_new(32, 1.0f);

//     // AVX double: each element becomes 2.0f
//     double_f32_avx_safe(*buf);

//     // Read back via raw pointer
//     const float* ptr = buf->as_ptr();
//     // ptr[0] == 2.0f, ptr[1] == 2.0f, ...

//     return 0;
// }

#include <cstdlib>   /* std::malloc, std::free */
#include <cassert>
#include "aligned_simd.h"

/* C++03 RAII wrapper — no auto, no nullptr, no move semantics */
class AlignedBufferHandle {
public:
    explicit AlignedBufferHandle(size_t size, float value)
        : ptr_(aligned_buffer_create(size, value))
    {
        assert(ptr_ != 0);  /* nullptr doesn't exist in C++03 */
    }

    ~AlignedBufferHandle() {
        aligned_buffer_destroy(ptr_);
    }

    size_t len() const {
        return aligned_buffer_len(ptr_);
    }

    const float* data() const {
        return aligned_buffer_as_ptr(ptr_);
    }

    void double_avx() {
        aligned_buffer_double_avx(ptr_);
    }

private:
    /* No copy — C++03 style: declare private, do not define */
    AlignedBufferHandle(const AlignedBufferHandle&);
    AlignedBufferHandle& operator=(const AlignedBufferHandle&);

    AlignedBufferF32* ptr_;
};

int main() {
    AlignedBufferHandle buf(32, 1.0f);  /* 32 floats, all 1.0 */

    buf.double_avx();                   /* AVX: each becomes 2.0 */

    const float* data = buf.data();
    assert(data[0] == 2.0f);

    return 0;
}
